# Generated by Django 5.1.7 on 2025-03-23 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cor',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira um código hexadecimal válido.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(default='teste backend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='sempre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='ultima_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
